### ISSUE TITLE
BUG!

### ISSUE THREAD

**Issue by jasonChang49** [377960738/laravel-goto-controller#1]
Route::get('/{category}/category_articles', [IndexController::class, 'category_articles']);

Route::get('manage/{id}/copy', 'SupplierController@copy')->where('id', '[0-9]+');

will fail, hope you can solve him, thank you.

**Comment by jasonChang49** [comment]
@377960738 
https://github.com/377960738/laravel-goto-controller/blob/master/src/link.ts#L13

I think it needs to be fixed here to

```
let reg = /((\:\:)|(->))(((get|post|any|resource|put|path|delete|options)\()|(match\(\s?\[(['"][a-zA-Z]+['"],?\s?)+\],))\s?['"]([\{\}a-zA-Z\d_/]+)?['"],\s?((['"][a-zA-Z\d_\\]+(@[a-zA-Z\d_]+){0,1}['"])|(\[(([a-zA-Z\d_\\]+::class)|(['"][a-zA-Z\d_\\]+['"])),\s?['"][a-zA-Z\d_]+['"]\])|([a-zA-Z\d_\\]+::class))\s?\)/;
```

**Comment by 377960738** [comment]
I have received it. Thank you for your feedback
