### ISSUE TITLE
BUG!

### ISSUE THREAD

**Issue by jasonChang49** [377960738/laravel-goto-controller#2]
Route::get('test-api', 'TestApiController@getIndex');

will fail, hope you can solve him, thank you.

**Comment by jasonChang49** [comment]
@377960738 
https://github.com/377960738/laravel-goto-controller/blob/master/src/link.ts#L13

I think it needs to be fixed here to
`
((\:\:)|(->))(((get|post|any|resource|put|path|delete|options)\()|(match\(\s?\[(['"][a-zA-Z]+['"],?\s?)+\],))\s?['"]([a-zA-Z\d_\--/]+(\{[a-zA-Z\d_\--/]+\??\})?)?['"],\s?((['"][a-zA-Z\d_\--\\]+(@[a-zA-Z\d_\--]+){0,1}['"])|(\[(([a-zA-Z\d_\--\\]+::class)|(['"][a-zA-Z\d_\--\\]+['"])),\s?['"][a-zA-Z\d_\--]+['"]\])|([a-zA-Z\d_\--\\]+::class))\s?\)
`

**Comment by 377960738** [comment]
Sorry for taking so long to reply you, the new version has been released

**Comment by jasonChang49** [comment]
> Sorry for taking so long to reply you, the new version has been released

"Thank you so much for your valuable contribution! Your dedication and hard work have made a significant impact on the project, and we truly appreciate it. 😊"
